---
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  groups:
    bundler:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  groups:
    gh-actions:
      patterns:
      - "*"
